### ISSUE TITLE
Linkedin connector does not compile OOTB

### ISSUE THREAD

**Issue by asequeira** [mulesoft/linkedin-connector#1]
[ERROR] The following icon file does not exist: /opt/jobvite-connector/src/main/java/../../../icons/jobvite-connector-24x16.png
[ERROR] error on execute: An error ocurred while the DevKit was generating Java code. Check the logs for further details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.845s
[INFO] Finished at: Wed May 09 09:41:16 PDT 2012
[INFO] Final Memory: 21M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mule.tools.devkit:mule-devkit-maven-plugin:3.3.0-EA:generate-sources (default-generate-sources) on project mule-module-jobvite: An error ocurred while the DevKit was generating Java code. Check the logs for further details. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Alejandro-Sequeiras-MacBook-Pro:jobvite-connector alejandrosequeira$ 
Alejandro-Sequeiras-MacBook-Pro:jobvite-connector alejandrosequeira$ cd ../linkedin-connector/
Alejandro-Sequeiras-MacBook-Pro:linkedin-connector alejandrosequeira$ mvn compile
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/mule/tools/devkit/mule-devkit-parent/3.2/mule-devkit-parent-3.2.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.mule.modules:mule-module-linkedin:1.1-SNAPSHOT (/opt/linkedin-connector/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.mule.tools.devkit:mule-devkit-parent:pom:3.2 in central (http://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 12 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by federecio** [comment]
Added missing repository tag to pom.xml
